services:
  mongo:
    image: mongo:7
    container_name: inventory-mongo
    ports:
      - "27017:27017"
    volumes:
      - inventory_mongo_data:/data/db
    networks:
      - microservices

volumes:
  inventory_mongo_data:

networks:
  core:
    external: true